from tkinter import *
import datetime
window = Tk()
window.geometry("400x400")
window.title("Age Calculator")
frame = Frame(master=window,height=300,width=300,bg="#d0efff")
lb1 = Label(frame,text="Enter Your Year of Birth",bg="#d0efff",fg="black",width=20)
lb2 = Label(frame,text="Enter Your Day of Birth ",bg="#d0efff",fg="black",width=20)
lb3 = Label(frame,text="Enter Your Month of Birth",bg="#d0efff",fg="black",width=20)
Day_entry = Entry(frame)
Year_entry=Entry(frame)
Month_entry = Entry(frame)
def calculate_age():
    Day = Day_entry.get()
    Year = Year_entry.get()
    Month = Month_entry.get()
    current_year = datetime.date.today().year
    Age = current_year-int(Year)
    Age_message=("\n",Age)
    textbox.insert(END,Age_message)
textbox=Text(bg="#d0efff",fg="black")
textbox.place(x=20,y=300)
Age_button = Button(frame,text="Calculate Age",command=calculate_age)
Age_button.place(x=20,y=200)
frame.place(x=20,y=0)
lb1.place(x=20,y=20)
Year_entry.place(x=20,y=40)
lb2.place(x=20,y=60)
Day_entry.place(x=20,y=90)
lb3.place(x=20,y=120)
Month_entry.place(x=20,y=150)
window.mainloop()